import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Home,Library,Plus,Heart,Shuffle,Repeat,Volume2,VolumeX,SkipBack,SkipForward,Play,Pause,Mic,Car,MoreHorizontal,Clock3,Wifi,WifiOff,Keyboard,Trash2,X,ArrowLeft,Disc3,UserRound,ExternalLink,ListMusic,ChevronRight,Check} from 'lucide-react';
import './style.css';
const APP_VERSION='6.9.0';
const UPDATE_MANIFEST='./update.json';

async function fetchUpdateManifest(){
  const r=await fetch(`${UPDATE_MANIFEST}?t=${Date.now()}`,{cache:'no-store',headers:{'cache-control':'no-cache'}});
  if(!r.ok) throw new Error(`update manifest ${r.status}`);
  return await r.json() as {version:string;build?:string;message?:string;mandatory?:boolean};
}
function isNewerVersion(remote:string,local:string){
  const a=remote.split('.').map(Number), b=local.split('.').map(Number);
  for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]||0,y=b[i]||0;if(x!==y)return x>y;}
  return false;
}
function UpdateGate({children}:{children:React.ReactNode}){
  const [state,setState]=useState<'checking'|'ready'|'updating'|'error'>('checking');
  const [progress,setProgress]=useState(0);
  const [message,setMessage]=useState('Controllo aggiornamenti…');
  const [remoteVersion,setRemoteVersion]=useState('');
  useEffect(()=>{
    let alive=true;
    const run=async()=>{
      try{
        setMessage('Controllo della versione più recente…');
        const manifest=await fetchUpdateManifest();
        if(!alive)return;
        if(!isNewerVersion(manifest.version,APP_VERSION)){setProgress(100);setState('ready');return;}
        setRemoteVersion(manifest.version); setState('updating'); setMessage(manifest.message||'È disponibile un nuovo aggiornamento.'); setProgress(15);
        if(!('serviceWorker' in navigator)){
          setProgress(100); setMessage('Aggiornamento pronto. Ricarico l’app…'); setTimeout(()=>location.reload(),500); return;
        }
        const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});
        setProgress(35); await reg.update(); setProgress(55);
        const installing=reg.installing;
        if(installing){await new Promise<void>(resolve=>{
          const handler=()=>{if(installing.state==='installed'||installing.state==='redundant'){installing.removeEventListener('statechange',handler);resolve();}};
          installing.addEventListener('statechange',handler); handler();
        });}
        setProgress(75);
        if(reg.waiting) reg.waiting.postMessage({type:'SKIP_WAITING'});
        await new Promise<void>(resolve=>{
          let done=false; const finish=()=>{if(done)return;done=true;navigator.serviceWorker.removeEventListener('controllerchange',finish);resolve();};
          navigator.serviceWorker.addEventListener('controllerchange',finish); setTimeout(finish,5000);
        });
        setProgress(92); setMessage(`Aggiornamento ${manifest.version} completato. Avvio Luma…`); sessionStorage.setItem('luma:lastUpdate',manifest.version); setProgress(100); setTimeout(()=>location.reload(),450);
      }catch(err){console.warn('Luma update check failed',err);if(!alive)return;setState('error');setMessage('Impossibile verificare gli aggiornamenti.');}
    };
    run(); return()=>{alive=false};
  },[]);
  if(state==='ready')return <>{children}</>;
  const retry=()=>location.reload();
  return <div className="startup-gate" role="status" aria-live="polite"><div className="startup-card">
    <div className="startup-logo">Luma<span>●</span></div>
    {state==='checking'&&<><div className="startup-spinner"/><h1>Controllo aggiornamenti</h1><p>{message}</p></>}
    {state==='updating'&&<><div className="startup-spinner"/><h1>Aggiornamento in corso</h1><p>{message}{remoteVersion&&<><br/><strong>Versione {remoteVersion}</strong></>}</p><div className="startup-progress"><i style={{width:`${progress}%`}}/></div><small>{progress}% · Non chiudere l’app</small></>}
    {state==='error'&&<><div className="startup-warning">!</div><h1>Controllo non riuscito</h1><p>{message}</p><button className="primary" onClick={retry}>Riprova</button><small>Luma non verrà avviata finché il controllo non sarà completato.</small></>}
    <footer>Versione installata {APP_VERSION}</footer>
  </div></div>;
}
if('serviceWorker'in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{}));
const API=import.meta.env.VITE_API_BASE_URL||'/api';
type Track={id:string;title:string;artist:string;album:string;artwork?:string;duration?:number;playable?:boolean;downloadable?:boolean;provider?:string;providerId?:string;externalUrl?:string;version?:string;isrc?:string};
type Album={id:string;title:string;artist:string;artwork?:string;releaseDate?:string;trackCount?:number;albumType?:string;provider?:string;providerId?:string;externalUrl?:string;tracks?:Track[];label?:string;copyrights?:string[]};
type Artist={id:string;name:string;image?:string;provider?:string;providerId?:string;externalUrl?:string;genres?:string[];followers?:number;popularity?:number;topTracks?:Track[];albums?:Album[]};
type Playlist={id:string;name:string;tracks:Track[]};
type HistoryItem=Track&{playedAt:number};
const PLACEHOLDER='https://placehold.co/600x600/17171d/fff?text=♪';
function read<T>(k:string,f:T):T{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function fmt(s?:number){if(!s||!Number.isFinite(s))return'0:00';return`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function useLibrary(){const[favorites,setFavorites]=useState<Track[]>(()=>read('luma:favorites',[]));const[playlists,setPlaylists]=useState<Playlist[]>(()=>read('luma:playlists',[]));const[history,setHistory]=useState<HistoryItem[]>(()=>read('luma:history',[]));const[albums,setAlbums]=useState<Album[]>(()=>read('luma:albums',[]));const[artists,setArtists]=useState<Artist[]>(()=>read('luma:artists',[]));
 useEffect(()=>localStorage.setItem('luma:favorites',JSON.stringify(favorites)),[favorites]);useEffect(()=>localStorage.setItem('luma:playlists',JSON.stringify(playlists)),[playlists]);useEffect(()=>localStorage.setItem('luma:history',JSON.stringify(history.slice(0,100))),[history]);useEffect(()=>localStorage.setItem('luma:albums',JSON.stringify(albums)),[albums]);useEffect(()=>localStorage.setItem('luma:artists',JSON.stringify(artists)),[artists]);
 const toggle=(t:Track)=>setFavorites(v=>v.some(x=>x.id===t.id)?v.filter(x=>x.id!==t.id):[...v,t]);const saveAlbum=(a:Album)=>setAlbums(v=>v.some(x=>x.id===a.id)?v.filter(x=>x.id!==a.id):[...v,a]);const followArtist=(a:Artist)=>setArtists(v=>v.some(x=>x.id===a.id)?v.filter(x=>x.id!==a.id):[...v,a]);const create=(name:string)=>setPlaylists(v=>[...v,{id:crypto.randomUUID(),name:name.trim(),tracks:[]}]);const rename=(pid:string,name:string)=>setPlaylists(v=>v.map(p=>p.id===pid?{...p,name:name.trim()||p.name}:p));const removePlaylist=(pid:string)=>setPlaylists(v=>v.filter(p=>p.id!==pid));const add=(pid:string,t:Track)=>setPlaylists(v=>v.map(p=>p.id===pid&&!p.tracks.some(x=>x.id===t.id)?{...p,tracks:[...p.tracks,t]}:p));const removeTrack=(pid:string,tid:string)=>setPlaylists(v=>v.map(p=>p.id===pid?{...p,tracks:p.tracks.filter(t=>t.id!==tid)}:p));const moveTrack=(pid:string,index:number,dir:-1|1)=>setPlaylists(v=>v.map(p=>{if(p.id!==pid)return p;const ni=index+dir;if(ni<0||ni>=p.tracks.length)return p;const tracks=[...p.tracks];[tracks[index],tracks[ni]]=[tracks[ni],tracks[index]];return {...p,tracks}}));const record=(t:Track)=>setHistory(v=>[{...t,playedAt:Date.now()},...v.filter(x=>x.id!==t.id)].slice(0,100));return{favorites,playlists,history,albums,artists,toggle,saveAlbum,followArtist,create,rename,removePlaylist,add,removeTrack,moveTrack,record,setPlaylists,setHistory}}
function App(){const lib=useLibrary();const audio=useRef<HTMLAudioElement|null>(null);const abort=useRef<AbortController|null>(null);const[q,setQ]=useState('');const[searching,setSearching]=useState(false);const[results,setResults]=useState<any>({artists:[],albums:[],tracks:[],pagination:{hasMore:false}});const[current,setCurrent]=useState<Track|null>(null);const[playing,setPlaying]=useState(false);const[pos,setPos]=useState(0);const[duration,setDuration]=useState(0);const[volume,setVolume]=useState(()=>Number(localStorage.getItem('luma:volume')||1));const[queue,setQueue]=useState<Track[]>([]);const[tab,setTab]=useState('home');const[auto,setAuto]=useState(false);const[repeat,setRepeat]=useState(false);const[shuffle,setShuffle]=useState(false);const[voice,setVoice]=useState(false);const[toast,setToast]=useState('');const[shortcuts,setShortcuts]=useState(false);const[detail,setDetail]=useState<{type:'artist'|'album';id:string;provider:string}|null>(null);const[loadingDetail,setLoadingDetail]=useState(false);const[playlistFor,setPlaylistFor]=useState<Track|null>(null);const[showFullPlayer,setShowFullPlayer]=useState(false);const[online,setOnline]=useState(navigator.onLine);
 useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);
 useEffect(()=>{if(!audio.current)audio.current=new Audio();const a=audio.current; a.volume=volume;const time=()=>{setPos(a.currentTime);setDuration(a.duration||0)};const play=()=>setPlaying(true),pause=()=>setPlaying(false),end=()=>{if(repeat){a.currentTime=0;a.play();return}next()};a.addEventListener('timeupdate',time);a.addEventListener('loadedmetadata',time);a.addEventListener('play',play);a.addEventListener('pause',pause);a.addEventListener('ended',end);return()=>{a.removeEventListener('timeupdate',time);a.removeEventListener('loadedmetadata',time);a.removeEventListener('play',play);a.removeEventListener('pause',pause);a.removeEventListener('ended',end)}},[repeat,queue,current]);
 useEffect(()=>localStorage.setItem('luma:volume',String(volume)),[volume]);useEffect(()=>{if('mediaSession'in navigator&&current){navigator.mediaSession.metadata=new MediaMetadata({title:current.title,artist:current.artist,album:current.album,artwork:[{src:current.artwork||PLACEHOLDER}]});[['play',()=>togglePlay()],['pause',()=>audio.current?.pause()],['nexttrack',()=>next()],['previoustrack',()=>prev()]].forEach(([n,fn])=>{try{navigator.mediaSession.setActionHandler(n as MediaSessionAction,fn as any)}catch{}})}},[current,queue,playing]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.tagName==='INPUT')return;if(e.code==='Space'){e.preventDefault();togglePlay()}if(e.key==='ArrowRight')seek(10);if(e.key==='ArrowLeft')seek(-10);if(e.key.toLowerCase()==='n')next();if(e.key.toLowerCase()==='p')prev();if(e.key.toLowerCase()==='m')setVolume(v=>v?0:1);if(e.key==='?')setShortcuts(v=>!v)};addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn)},[current,queue,playing]);
 useEffect(()=>{if(toast){const x=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(x)}},[toast]);
 async function search(page=0){if(!q.trim())return;abort.current?.abort();const c=new AbortController();abort.current=c;setSearching(true);try{const r=await fetch(`${API}/api/search?q=${encodeURIComponent(q)}&offset=${page*10}`,{signal:c.signal}).then(x=>x.json());setResults(r);setTab('search')}catch(e:any){if(e.name!=='AbortError')setToast('Ricerca non riuscita')}finally{if(!c.signal.aborted)setSearching(false)}}
 useEffect(()=>{if(!q.trim())return;const t=setTimeout(()=>search(0),450);return()=>clearTimeout(t)},[q]);
 async function resolve(t:Track){if(!t.provider||!t.providerId)return null;try{return(await fetch(`${API}/api/resolve/${t.provider}/${encodeURIComponent(t.providerId)}`).then(x=>x.json())).streamUrl||null}catch{return null}}
 async function play(t:Track,append=true){const u=await resolve(t);if(!u){if(t.externalUrl)window.open(t.externalUrl,'_blank','noopener,noreferrer');else setToast('Nessuna sorgente riproducibile');return}if(append)setQueue(v=>v.some(x=>x.id===t.id)?v:[...v,t]);setCurrent(t);lib.record(t);setPos(0);setTimeout(()=>{if(audio.current){audio.current.src=u;audio.current.volume=volume;audio.current.play().catch(()=>setToast('Premi Play per avviare'))}},0)}
 function next(){if(!queue.length)return;const i=current?queue.findIndex(x=>x.id===current.id):-1;let n=shuffle?Math.floor(Math.random()*queue.length):i+1;if(n>=queue.length)n=0;play(queue[n],false)}function prev(){if(!audio.current)return;if(audio.current.currentTime>5){audio.current.currentTime=0;return}const i=current?queue.findIndex(x=>x.id===current.id):-1;if(i>0)play(queue[i-1],false)}function togglePlay(){if(!audio.current)return;if(audio.current.paused)audio.current.play().catch(()=>{});else audio.current.pause()}function seek(v:number){if(audio.current)audio.current.currentTime=Math.max(0,Math.min(audio.current.duration||Infinity,audio.current.currentTime+v))}
 async function openDetail(type:'artist'|'album',provider:string,id:string){setDetail({type,provider,id});setLoadingDetail(true);try{const path=type==='artist'?`/api/artists/${provider}/${id}`:`/api/albums/${provider}/${id}`;const d=await fetch(API+path).then(x=>x.json());setDetailData(d)}catch{setToast('Dettaglio non disponibile')}finally{setLoadingDetail(false)}}
 const[detailData,setDetailData]=useState<any>(null);useEffect(()=>{setDetailData(null)},[detail]);
 function startVoice(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR)return setToast('Voce non supportata');const r=new SR();r.lang='it-IT';r.onresult=(e:any)=>{setQ(e.results[0][0].transcript);setVoice(false)};r.onend=()=>setVoice(false);setVoice(true);r.start()}
 const isFav=(t:Track)=>lib.favorites.some(x=>x.id===t.id);const isSavedAlbum=(a:Album)=>lib.albums.some(x=>x.id===a.id);const isFollowed=(a:Artist)=>lib.artists.some(x=>x.id===a.id);
 function trackRow(t:Track,i?:number){return <div className="trackrow"><button className="coverbtn" onClick={()=>play(t)}><img src={t.artwork||PLACEHOLDER}/>{i!==undefined&&<span>{i+1}</span>}</button><div className="trackmeta" onDoubleClick={()=>play(t)}><b>{t.title}</b><small>{t.artist}{t.album?` · ${t.album}`:''}</small></div><span className="version">{t.version&&t.version!=='original'?t.version:''}</span><span className="dur">{fmt(t.duration)}</span><button className={isFav(t)?'icon active':'icon'} onClick={()=>lib.toggle(t)}><Heart fill={isFav(t)?'currentColor':'none'}/></button><button className="icon" onClick={()=>setPlaylistFor(t)}><Plus/></button><button className="icon" onClick={()=>setQueue(v=>v.some(x=>x.id===t.id)?v:[...v,t])}><MoreHorizontal/></button></div>}
 function albumCard(a:Album){return <button className="card" onClick={()=>a.provider&&a.providerId&&openDetail('album',a.provider,a.providerId)}><img src={a.artwork||PLACEHOLDER}/><b>{a.title}</b><small>{a.artist}</small><small>{a.releaseDate?.slice(0,4)||'—'} · {a.albumType||'album'}</small></button>}
 function home(){return <><section className="hero"><div><span className="eyebrow">LUMA MUSIC</span><h1>La tua musica,<br/><em>senza complicazioni.</em></h1><p>Cerca artisti, album e brani. Luma unifica i cataloghi e trova automaticamente le sorgenti disponibili.</p><button className="primary" onClick={()=>document.querySelector<HTMLInputElement>('.search input')?.focus()}>Inizia a cercare <ChevronRight/></button></div><div className="heroorb">♪</div></section><Section title="Riprendi da dove eri" icon={<Clock3/>}>{lib.history.length?<div className="tracklist">{lib.history.slice(0,5).map((t,i)=>trackRow(t,i))}</div>:<Empty text="La cronologia apparirà qui dopo il primo ascolto."/>}</Section><Section title="Album salvati" icon={<Disc3/>}>{lib.albums.length?<div className="cards">{lib.albums.slice(0,6).map(albumCard)}</div>:<Empty text="Salva un album dalla pagina artista o dai risultati."/>}</Section></>}
 function searchView(){return <><div className="viewhead"><div><span className="eyebrow">RICERCA</span><h2>{q?`Risultati per “${q}”`:'Cerca nella tua musica'}</h2></div><span className="providerpill">{online?<><Wifi/> Online</>:<><WifiOff/> Offline</>}</span></div>{searching&&<div className="skeletonline"/>}{results.artists?.length>0&&<Section title="Artisti"><div className="cards">{results.artists.slice(0,8).map((a:any)=><button className="card artistcard" key={a.id} onClick={()=>openDetail('artist',a.provider,a.providerId)}><img src={a.image||PLACEHOLDER}/><b>{a.name}</b><small>Artista</small></button>)}</div></Section>}{results.albums?.length>0&&<Section title="Album"><div className="cards">{results.albums.slice(0,8).map((a:any)=>albumCard(a))}</div></Section>}<Section title="Brani"><div className="tracklist">{results.tracks?.length?results.tracks.map((t:Track,i:number)=>trackRow(t,i)):<Empty text={q?'Nessun brano trovato.':'Inizia digitando qualcosa nella barra di ricerca.'}/>}</div>{results.pagination?.hasMore&&<button className="secondary load" onClick={()=>search(Math.floor((results.pagination.offset||0)/10)+1)}>Carica altri</button>}</Section></>}
 function detailView(){if(!detail)return null;if(loadingDetail)return <div className="loadingbig">Caricamento…</div>;if(!detailData)return <Empty text="Dettaglio non disponibile."/>;if(detail.type==='artist'){const a=detailData as Artist;return <><button className="back" onClick={()=>setDetail(null)}><ArrowLeft/> Indietro</button><section className="profilehero"><img src={a.image||PLACEHOLDER}/><div><span className="eyebrow">ARTISTA</span><h1>{a.name}</h1><p>{a.genres?.slice(0,4).join(' · ')||'Artista'}</p><div className="actions"><button className="primary" onClick={()=>a.topTracks?.[0]&&play(a.topTracks[0])}><Play/> Riproduci</button><button className="secondary" onClick={()=>a.topTracks&&setQueue(a.topTracks)}><Shuffle/> Shuffle</button><button className={isFollowed(a)?'secondary active':'secondary'} onClick={()=>lib.followArtist(a)}><Heart fill={isFollowed(a)?'currentColor':'none'}/> {isFollowed(a)?'Seguito':'Segui'}</button>{a.externalUrl&&<a className="secondary linkbtn" href={a.externalUrl} target="_blank"><ExternalLink/> Provider</a>}</div></div></section><Section title="Brani popolari"><div className="tracklist">{a.topTracks?.map((t,i)=>trackRow(t,i))}</div></Section><Section title="Discografia"><div className="cards">{a.albums?.map(albumCard)}</div></Section></>}
 const a=detailData as Album;return <><button className="back" onClick={()=>setDetail(null)}><ArrowLeft/> Indietro</button><section className="albumhero"><img src={a.artwork||PLACEHOLDER}/><div><span className="eyebrow">{a.albumType||'ALBUM'}</span><h1>{a.title}</h1><h3>{a.artist}</h3><p>{a.releaseDate?.slice(0,4)||'—'} · {a.trackCount||a.tracks?.length||0} brani {a.label?` · ${a.label}`:''}</p><div className="actions"><button className="primary" onClick={()=>a.tracks?.[0]&&play(a.tracks[0])}><Play/> Riproduci</button><button className="secondary" onClick={()=>{if(a.tracks?.length){setQueue(a.tracks);play(a.tracks[0],false)}}}><Shuffle/> Shuffle</button><button className={isSavedAlbum(a)?'secondary active':'secondary'} onClick={()=>lib.saveAlbum(a)}><Heart fill={isSavedAlbum(a)?'currentColor':'none'}/> {isSavedAlbum(a)?'Salvato':'Salva'}</button></div></div></section><Section title="Tracklist"><div className="tracklist">{a.tracks?.map((t,i)=>trackRow(t,i))}</div></Section>{a.copyrights?.length?<div className="legal">{a.copyrights.join(' · ')}</div>:null}</>}
 function library(){return <><div className="viewhead"><div><span className="eyebrow">LIBRERIA</span><h2>Tutto ciò che hai salvato</h2></div><button className="primary" onClick={()=>{const n=prompt('Nome playlist');if(n?.trim())lib.create(n)}}><Plus/> Nuova playlist</button></div><Section title={`Brani preferiti · ${lib.favorites.length}`}><div className="tracklist">{lib.favorites.length?lib.favorites.map((t,i)=>trackRow(t,i)):<Empty text="Premi il cuore su un brano per salvarlo."/>}</div></Section><Section title={`Album salvati · ${lib.albums.length}`}><div className="cards">{lib.albums.length?lib.albums.map(albumCard):<Empty text="Salva un album per trovarlo qui."/>}</div></Section><Section title={`Artisti seguiti · ${lib.artists.length}`}><div className="cards">{lib.artists.length?lib.artists.map(a=><button className="card artistcard" key={a.id} onClick={()=>openDetail('artist',a.provider||'spotify',a.providerId||a.id.replace('spotify:',''))}><img src={a.image||PLACEHOLDER}/><b>{a.name}</b><small>Seguito</small></button>):<Empty text="Segui un artista per ritrovarlo qui."/>}</div></Section><Section title={`Playlist · ${lib.playlists.length}`}><div className="playlistgrid">{lib.playlists.length?lib.playlists.map(p=><div className="playlistcard" key={p.id}><button className="playlistmain" onClick={()=>{setQueue(p.tracks);if(p.tracks[0])play(p.tracks[0],false)}}><ListMusic/><b>{p.name}</b><small>{p.tracks.length} brani</small></button><div className="playlistactions"><button className="icon" title="Rinomina" onClick={()=>{const n=prompt('Nuovo nome',p.name);if(n?.trim())lib.rename(p.id,n)}}>✎</button><button className="icon" title="Elimina" onClick={()=>{if(confirm(`Eliminare “${p.name}”?`))lib.removePlaylist(p.id)}}><Trash2/></button></div></div>):<Empty text="Crea la tua prima playlist."/>}</div></Section><Section title="Cronologia"><div className="tracklist">{lib.history.length?lib.history.slice(0,20).map((t,i)=><div className="trackrow" key={`${t.id}-${t.playedAt}`}><button className="coverbtn" onClick={()=>play(t)}><img src={t.artwork||PLACEHOLDER}/></button><div className="trackmeta"><b>{t.title}</b><small>{t.artist} · {new Date(t.playedAt).toLocaleDateString('it-IT')}</small></div><button className="icon" onClick={()=>play(t)}><Play/></button></div>):<Empty text="I brani ascoltati appariranno qui."/>}</div></Section></>}
 const content=detail?detailView():tab==='home'?home():tab==='search'?searchView():library();return <div className={auto?'app auto':'app'}><aside className="sidebar"><div className="brand">Luma<span>●</span></div><button className={tab==='home'?'navactive':''} onClick={()=>{setDetail(null);setTab('home')}}><Home/> Home</button><button className={tab==='search'?'navactive':''} onClick={()=>{setDetail(null);setTab('search')}}><Search/> Cerca</button><button className={tab==='library'?'navactive':''} onClick={()=>{setDetail(null);setTab('library')}}><Library/> Libreria</button><button onClick={()=>setAuto(v=>!v)}><Car/> Auto Mode</button><button onClick={()=>setShortcuts(true)}><Keyboard/> Scorciatoie</button><div className="sidefoot">{online?<><Wifi/> Online</>:<><WifiOff/> Offline</>}</div></aside><main><header><div className="search"><Search/><input aria-label="Cerca musica" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Cerca artista, brano o album…"/><button onClick={startVoice} aria-label="Ricerca vocale"><Mic/></button></div></header><div className="content">{content}</div></main><nav className="bottomnav"><button onClick={()=>setTab('home')}><Home/>Home</button><button onClick={()=>setTab('search')}><Search/>Cerca</button><button onClick={()=>setTab('library')}><Library/>Libreria</button><button onClick={()=>setAuto(v=>!v)}><Car/>Auto</button></nav>{current&&<div className="player"><button className="playercover" onClick={()=>setShowFullPlayer(true)}><img src={current.artwork||PLACEHOLDER}/></button><div className="now" onClick={()=>setShowFullPlayer(true)}><b>{current.title}</b><small>{current.artist}</small></div><button className="icon" onClick={()=>lib.toggle(current)}><Heart fill={isFav(current)?'currentColor':'none'}/></button><button className="icon desktop" onClick={()=>setShuffle(v=>!v)}><Shuffle className={shuffle?'active':''}/></button><button className="icon desktop" onClick={prev}><SkipBack/></button><button className="playbtn" onClick={togglePlay}>{playing?<Pause/>:<Play/>}</button><button className="icon desktop" onClick={next}><SkipForward/></button><button className="icon desktop" onClick={()=>setRepeat(v=>!v)}><Repeat className={repeat?'active':''}/></button><div className="seek"><span>{fmt(pos)}</span><input type="range" min="0" max={duration||1} value={Math.min(pos,duration||1)} onChange={e=>{if(audio.current)audio.current.currentTime=Number(e.target.value)}}/><span>{fmt(duration)}</span></div><div className="volume desktop"><Volume2/><input type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></div></div>}
 {showFullPlayer&&current&&<div className="modal playerfull"><button className="close" onClick={()=>setShowFullPlayer(false)}><X/></button><img src={current.artwork||PLACEHOLDER}/><span className="eyebrow">IN RIPRODUZIONE</span><h2>{current.title}</h2><p>{current.artist} · {current.album}</p><input type="range" min="0" max={duration||1} value={pos} onChange={e=>{if(audio.current)audio.current.currentTime=Number(e.target.value)}}/><div className="fullcontrols"><button onClick={prev}><SkipBack/></button><button className="playbtn big" onClick={togglePlay}>{playing?<Pause/>:<Play/>}</button><button onClick={next}><SkipForward/></button></div></div>}
 {playlistFor&&<div className="modalshade"><div className="modalbox"><button className="close" onClick={()=>setPlaylistFor(null)}><X/></button><h3>Aggiungi a playlist</h3>{lib.playlists.length?lib.playlists.map(p=><button className="playlistchoice" onClick={()=>{lib.add(p.id,playlistFor);setPlaylistFor(null);setToast(`Aggiunto a ${p.name}`)}}><ListMusic/>{p.name}<ChevronRight/></button>):<Empty text="Crea prima una playlist dalla Libreria."/>}<button className="secondary" onClick={()=>{const n=prompt('Nome playlist');if(n){lib.create(n);setToast('Playlist creata')}}}><Plus/> Nuova playlist</button></div></div>}
 {shortcuts&&<div className="modalshade"><div className="modalbox"><button className="close" onClick={()=>setShortcuts(false)}><X/></button><h3>Scorciatoie</h3><p><kbd>Space</kbd> Play/Pausa</p><p><kbd>←</kbd> <kbd>→</kbd> ±10 secondi</p><p><kbd>N</kbd> prossimo · <kbd>P</kbd> precedente</p><p><kbd>M</kbd> mute</p><button className="primary" onClick={()=>setShortcuts(false)}>Chiudi</button></div></div>}{toast&&<div className="toast">{toast}</div>}</div>}
function Section({title,icon,children}:{title:string;icon?:React.ReactNode;children:React.ReactNode}){return <section className="section"><div className="sectionhead"><h3>{icon}{title}</h3></div>{children}</section>}
function Empty({text}:{text:string}){return <div className="empty"><MusicIcon/><span>{text}</span></div>}
function MusicIcon(){return <Disc3/>}
createRoot(document.getElementById('root')!).render(<UpdateGate><App/></UpdateGate>);
